import http from 'node:http';
import crypto from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { WebSocketServer } from 'ws';
const PORT=Number(process.env.PORT||3000),MAX_PLAYERS=4,WORLD={width:1600,height:900},TICK=30,players=new Map(),rooms=new Map();
const id=()=>crypto.randomBytes(4).toString('hex');
const code=()=>{let c;do c=Math.random().toString(36).slice(2,8).toUpperCase();while(rooms.has(c));return c};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const send=(ws,d)=>{if(ws.readyState===1)ws.send(JSON.stringify(d))};
const broadcast=(r,d)=>r.players.forEach(p=>send(p.ws,d));
const snapshot=r=>({type:'state',players:r.players.map(p=>({id:p.id,name:p.name,x:p.x,y:p.y,hp:p.hp,score:p.score,color:p.color})),boss:r.boss,bullets:r.bullets.map(b=>({id:b.id,owner:b.owner,x:b.x,y:b.y,vx:b.vx,vy:b.vy})),phase:r.phase});
function createRoom(){const c=code(),r={code:c,players:[],bullets:[],phase:'waiting',boss:{x:800,y:180,hp:300,maxHp:300,angle:0,modules:[80,80,80,80,80,80]}};rooms.set(c,r);return r}
function reset(r){r.phase='playing';r.bullets=[];r.boss.hp=r.boss.maxHp;r.boss.angle=0;r.boss.modules=[80,80,80,80,80,80];r.players.forEach((p,i)=>{p.x=350+(i%2)*900;p.y=620+Math.floor(i/2)*80;p.hp=100;p.score=0})}
function leave(p){const r=p.room;if(!r)return;r.players=r.players.filter(x=>x!==p);players.delete(p.id);broadcast(r,{type:'room',count:r.players.length,max:MAX_PLAYERS});if(!r.players.length)rooms.delete(r.code)}
function fire(r,p){if(p.cooldown>0||p.hp<=0||r.phase!=='playing')return;p.cooldown=7;const dx=r.boss.x-p.x,dy=r.boss.y-p.y,l=Math.hypot(dx,dy)||1;r.bullets.push({id:id(),owner:p.id,x:p.x,y:p.y,vx:dx/l*14,vy:dy/l*14,life:100})}
setInterval(()=>{for(const r of rooms.values()){if(r.phase==='playing'){r.boss.angle+=.015;r.boss.x=800+Math.sin(r.boss.angle)*260;for(const p of r.players){p.x=clamp(p.x+p.input.x*7,30,1570);p.y=clamp(p.y+p.input.y*7,300,870);if(p.cooldown>0)p.cooldown--}const next=[];for(const b of r.bullets){b.x+=b.vx;b.y+=b.vy;b.life--;if(b.life<=0||b.x<-20||b.x>1620||b.y<-20||b.y>920)continue;if(Math.hypot(b.x-r.boss.x,b.y-r.boss.y)<105){r.boss.hp=Math.max(0,r.boss.hp-4);const p=r.players.find(x=>x.id===b.owner);if(p)p.score+=4;continue}next.push(b)}r.bullets=next;if(r.boss.hp<=0)r.phase='won'}broadcast(r,snapshot(r))}},1000/TICK);
const server=http.createServer(async(req,res)=>{if(req.url==='/health'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true,rooms:rooms.size}))}if(req.url==='/'||req.url==='/index.html'){try{const html=await readFile(new URL('./public/index.html',import.meta.url));res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(html)}catch{res.writeHead(500);return res.end('Client unavailable')}}res.writeHead(404);res.end('Not found')});
const wss=new WebSocketServer({server});
wss.on('connection',ws=>{const p={id:id(),ws,room:null,name:'Pilot',x:800,y:650,hp:100,score:0,color:'#7dd3fc',cooldown:0,input:{x:0,y:0}};players.set(p.id,p);send(ws,{type:'hello',id:p.id,maxPlayers:MAX_PLAYERS,world:WORLD});ws.on('message',raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return}if(m.type==='create'){if(p.room)return;join(createRoom(),p,m.name);return}if(m.type==='join'){if(p.room)return;const r=rooms.get(String(m.code||'').toUpperCase());if(!r)return send(ws,{type:'error',message:'Комната не найдена'});if(r.players.length>=MAX_PLAYERS)return send(ws,{type:'error',message:'Комната заполнена'});join(r,p,m.name);return}if(!p.room)return;if(m.type==='input'){p.input.x=clamp(Number(m.x)||0,-1,1);p.input.y=clamp(Number(m.y)||0,-1,1)}else if(m.type==='fire')fire(p.room,p);else if((m.type==='start'||m.type==='restart')&&p.room.players[0]===p)reset(p.room)});ws.on('close',()=>leave(p))});
function join(r,p,name){p.room=r;p.name=String(name||'Pilot').slice(0,16);p.color=['#7dd3fc','#a78bfa','#fb7185','#fbbf24'][r.players.length];r.players.push(p);send(p.ws,{type:'joined',code:r.code,playerId:p.id,count:r.players.length,max:MAX_PLAYERS});broadcast(r,{type:'room',count:r.players.length,max:MAX_PLAYERS,code:r.code});if(r.players.length===1)reset(r)}
server.listen(PORT,()=>console.log(`Boss server listening on ${PORT}`));
