import http from 'node:http';
import crypto from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { WebSocketServer } from 'ws';

const PORT=Number(process.env.PORT||3000),MAX_PLAYERS=4,WORLD={width:1600,height:900},TICK=30,players=new Map(),rooms=new Map();
const id=()=>crypto.randomBytes(4).toString('hex');
const code=()=>{let c;do c=Math.random().toString(36).slice(2,8).toUpperCase();while(rooms.has(c));return c};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const send=(ws,d)=>{if(ws.readyState===1)ws.send(JSON.stringify(d))};
const broadcast=(r,d)=>r.players.forEach(p=>send(p.ws,d));
const roomPlayers=r=>r.players.map((p,i)=>({id:p.id,name:p.name,x:p.x,y:p.y,hp:p.hp,score:p.score,color:p.color,host:i===0}));
const snapshot=r=>({type:'state',players:roomPlayers(r),boss:r.boss,bullets:r.bullets.map(b=>({id:b.id,owner:b.owner,x:b.x,y:b.y,vx:b.vx,vy:b.vy,enemy:!!b.enemy})),phase:r.phase});
function roomInfo(r){return {type:'room',count:r.players.length,max:MAX_PLAYERS,code:r.code,phase:r.phase,players:roomPlayers(r)}}
function createRoom(){const c=code(),r={code:c,players:[],bullets:[],phase:'waiting',boss:{x:800,y:220,hp:300,maxHp:300,angle:0,modules:[80,80,80,80,80,80],shotTimer:0}};rooms.set(c,r);return r}
function reset(r){r.phase='playing';r.bullets=[];r.boss.hp=r.boss.maxHp;r.boss.angle=0;r.boss.shotTimer=0;r.boss.modules=[80,80,80,80,80,80];r.players.forEach((p,i)=>{p.x=350+(i%2)*900;p.y=650+Math.floor(i/2)*70;p.hp=100;p.score=0;p.cooldown=0})}
function leave(p){const r=p.room;if(!r)return;r.players=r.players.filter(x=>x!==p);players.delete(p.id);if(!r.players.length){rooms.delete(r.code);return}if(r.phase==='playing'&&r.players.length===0)r.phase='waiting';broadcast(r,roomInfo(r))}
function fire(r,p){if(p.cooldown>0||p.hp<=0||r.phase!=='playing')return;p.cooldown=7;const dx=r.boss.x-p.x,dy=r.boss.y-p.y,l=Math.hypot(dx,dy)||1;r.bullets.push({id:id(),owner:p.id,x:p.x,y:p.y,vx:dx/l*14,vy:dy/l*14,life:100,enemy:false})}
function bossFire(r){const live=r.players.filter(p=>p.hp>0);if(!live.length)return;const target=live[Math.floor(Math.random()*live.length)],dx=target.x-r.boss.x,dy=target.y-r.boss.y,l=Math.hypot(dx,dy)||1;r.bullets.push({id:id(),owner:'boss',x:r.boss.x,y:r.boss.y,vx:dx/l*5.2,vy:dy/l*5.2,life:190,enemy:true})}
setInterval(()=>{for(const r of rooms.values()){if(r.phase==='playing'){r.boss.angle+=.015;r.boss.x=800+Math.sin(r.boss.angle)*260;r.boss.shotTimer--;if(r.boss.shotTimer<=0){bossFire(r);r.boss.shotTimer=28}for(const p of r.players){p.x=clamp(p.x+p.input.x*7,40,1560);p.y=clamp(p.y+p.input.y*7,430,850);if(p.cooldown>0)p.cooldown--}const next=[];for(const b of r.bullets){b.x+=b.vx;b.y+=b.vy;b.life--;if(b.life<=0||b.x<-30||b.x>1630||b.y<-30||b.y>930)continue;if(!b.enemy&&Math.hypot(b.x-r.boss.x,b.y-r.boss.y)<110){r.boss.hp=Math.max(0,r.boss.hp-4);const p=r.players.find(x=>x.id===b.owner);if(p)p.score+=4;continue}if(b.enemy){const p=r.players.find(x=>x.hp>0&&Math.hypot(b.x-x.x,b.y-x.y)<28);if(p){p.hp=Math.max(0,p.hp-10);continue}}next.push(b)}r.bullets=next;if(r.boss.hp<=0)r.phase='won';if(r.players.length&&r.players.every(p=>p.hp<=0))r.phase='lost'}broadcast(r,snapshot(r))}},1000/TICK);

const server=http.createServer(async(req,res)=>{if(req.url==='/health'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true,rooms:rooms.size}))}if(req.url==='/'||req.url==='/index.html'){try{const html=await readFile(new URL('./public/index.html',import.meta.url));res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-cache'});return res.end(html)}catch{res.writeHead(500);return res.end('Client unavailable')}}res.writeHead(404);res.end('Not found')});
const wss=new WebSocketServer({server});
wss.on('connection',ws=>{const p={id:id(),ws,room:null,name:'Pilot',x:800,y:650,hp:100,score:0,color:'#7dd3fc',cooldown:0,input:{x:0,y:0}};players.set(p.id,p);send(ws,{type:'hello',id:p.id,maxPlayers:MAX_PLAYERS,world:WORLD});ws.on('message',raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return}if(m.type==='create'){if(p.room)return;join(createRoom(),p,m.name);return}if(m.type==='join'){if(p.room)return;const r=rooms.get(String(m.code||'').toUpperCase());if(!r)return send(ws,{type:'error',message:'Комната не найдена'});if(r.players.length>=MAX_PLAYERS)return send(ws,{type:'error',message:'Комната заполнена'});if(r.phase!=='waiting')return send(ws,{type:'error',message:'Игра уже началась'});join(r,p,m.name);return}if(!p.room)return;if(m.type==='input'){p.input.x=clamp(Number(m.x)||0,-1,1);p.input.y=clamp(Number(m.y)||0,-1,1)}else if(m.type==='fire')fire(p.room,p);else if(m.type==='start'){if(p.room.players[0]===p&&p.room.phase==='waiting')reset(p.room)}else if(m.type==='restart'){if(p.room.players[0]===p)reset(p.room) ;else return}if(m.type==='start'||m.type==='restart')broadcast(p.room,roomInfo(p.room))});ws.on('close',()=>leave(p))});
function join(r,p,name){p.room=r;p.name=String(name||'Pilot').slice(0,16);p.color=['#63d8ff','#b58cff','#ff6b9a','#ffd166'][r.players.length];r.players.push(p);send(p.ws,{type:'joined',code:r.code,playerId:p.id,count:r.players.length,max:MAX_PLAYERS,host:r.players[0]===p,players:roomPlayers(r)});broadcast(r,roomInfo(r))}
server.listen(PORT,()=>console.log(`Boss server listening on ${PORT}`));
