export class Renderer {
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.camera=null;this.resize();addEventListener('resize',()=>this.resize());}
  setCamera(camera){this.camera=camera;camera.resize(this.w,this.h);}
  resize(){const d=Math.min(devicePixelRatio||1,2);this.canvas.width=innerWidth*d;this.canvas.height=innerHeight*d;this.canvas.style.width='100%';this.canvas.style.height='100%';this.ctx.setTransform(d,0,0,d,0,0);this.w=innerWidth;this.h=innerHeight;if(this.camera)this.camera.resize(this.w,this.h);}
  clear(){const c=this.ctx;c.fillStyle='#05030d';c.fillRect(0,0,this.w,this.h);}
  circle(x,y,r,fill,stroke){const c=this.ctx;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=2;c.stroke();}}
  screen(x,y){return this.camera?this.camera.toScreen(x,y):{x,y};}
  drawArena(arena){const c=this.ctx;c.save();const p=this.screen(arena.cx,arena.cy);const g=c.createRadialGradient(p.x,p.y,20,p.x,p.y,arena.radius);g.addColorStop(0,'#17112c');g.addColorStop(.72,'#090817');g.addColorStop(1,'#03030a');this.circle(p.x,p.y,arena.radius,g,'#6e4ed0');c.beginPath();c.arc(p.x,p.y,arena.radius-10,0,Math.PI*2);c.strokeStyle='rgba(191,130,255,.18)';c.lineWidth=2;c.stroke();for(let i=1;i<9;i++){c.beginPath();c.arc(p.x,p.y,arena.radius*i/9,0,Math.PI*2);c.strokeStyle='rgba(130,110,190,.055)';c.stroke();}for(let i=0;i<72;i++){const a=i*Math.PI*2/72;c.beginPath();c.moveTo(p.x+Math.cos(a)*arena.radius,p.y+Math.sin(a)*arena.radius);c.lineTo(p.x+Math.cos(a)*(arena.radius-12),p.y+Math.sin(a)*(arena.radius-12));c.strokeStyle='rgba(200,160,255,.18)';c.stroke();}c.restore();}
  drawPlayer(p){const c=this.ctx,s=this.screen(p.x,p.y);c.save();c.translate(s.x,s.y);c.rotate(p.angle);c.shadowBlur=16;c.shadowColor='#58dfff';c.beginPath();c.moveTo(23,0);c.lineTo(-14,-13);c.lineTo(-7,0);c.lineTo(-14,13);c.closePath();c.fillStyle='#59dfff';c.fill();c.shadowBlur=0;c.strokeStyle='#effcff';c.stroke();c.restore();}
  drawBoss(b){const c=this.ctx,s=this.screen(b.x,b.y);c.save();c.translate(s.x,s.y);c.rotate(b.angle*.35);this.circle(0,0,b.radius,'#171126','#8d62df');for(let i=0;i<12;i++){const a=i*Math.PI*2/12;c.save();c.rotate(a);c.fillStyle=i%2?'#261842':'#211538';c.fillRect(-22,-116,44,34);c.restore();}for(const m of b.modules){if(!m.alive)continue;const fill=m.type==='core'?'#ffd34e':m.type==='cannon'?'#ff557a':m.type==='shield'?'#66d9ff':'#9b70ff';const p={x:m.x,y:m.y};c.save();const a=b.angle*.35;c.translate(p.x*Math.cos(a)-p.y*Math.sin(a),p.x*Math.sin(a)+p.y*Math.cos(a));c.rotate(-a);c.fillStyle=fill;c.strokeStyle='#f4edff';c.lineWidth=2;c.fillRect(-m.w/2,-m.h/2,m.w,m.h);c.strokeRect(-m.w/2,-m.h/2,m.w,m.h);if(m.type==='core'){c.fillStyle='#fff4a8';c.fillRect(-15,-15,30,30);}c.fillStyle='rgba(0,0,0,.65)';c.fillRect(-m.w/2,m.h/2+7,m.w,5);c.fillStyle='#65e69b';c.fillRect(-m.w/2,m.h/2+7,m.w*Math.max(0,m.hp/m.maxHp),5);c.restore();}c.restore();}
  drawProjectiles(ps){for(const p of ps){const s=this.screen(p.x,p.y);if(p.owner==='player')this.circle(s.x,s.y,p.radius,'#ffe66b');else{this.circle(s.x,s.y,p.radius,'#ff668b');if(p.radius>10)this.circle(s.x,s.y,p.radius+8,'rgba(255,90,120,.10)','#ff668b');}}}
  drawWarnings(warnings){const c=this.ctx;for(const w of warnings){const s=this.screen(w.x,w.y);c.save();c.globalAlpha=Math.max(0,Math.min(1,w.alpha));c.strokeStyle='#ff5e7d';c.lineWidth=3;c.setLineDash([8,8]);c.beginPath();c.arc(s.x,s.y,w.r,0,Math.PI*2);c.stroke();c.setLineDash([]);c.fillStyle='rgba(255,65,100,.10)';c.fill();c.restore();}}
  drawResult(text){const c=this.ctx;c.fillStyle='rgba(0,0,0,.58)';c.fillRect(0,0,this.w,this.h);c.fillStyle='#fff';c.font='900 36px system-ui';c.textAlign='center';c.fillText(text,this.w/2,this.h/2);}
}
